; safe global key remaps which should always exist
(bind-key* "\M-/"    'find-tag-other-window)
(bind-key* "\C-f" 'grep)
(bind-key* "\M-f" 'my-grep)
(bind-key* "\M-d" 'delete-word)
(bind-key* "\M-," 'lgrep)
(bind-key* [S-return] 'cua-set-rectangle-mark)
(bind-key* [M-return] 'cua-set-mark)
(bind-key* "\M-," 'lgrep)
;; go to specific line in current buffer
(bind-key* "\C-cg" 'goto-lineg)

;; Eat space at point up to non-space
(bind-key* "\C-ce" 'fixup-whitespace)
(bind-key* "\C-xk" 'kill-current-buffer)
(bind-key* "\C-x\C-k" 'kill-current-buffer)

(bind-key* "\C-cn" 'increment-number-at-point)
(bind-key* "\C-c\C-n" 'increment-number-at-point)
;; Remap Home and End keys to move within current line, and
;; C-Home and C-End keys to beginning and end of buffer
(bind-key* [(home)] 'beginning-of-line)
(bind-key* [(end)] 'end-of-line)
(bind-key* [(control home)] 'beginning-of-buffer)
(bind-key* "\C-xt" 'beginning-of-buffer)
(bind-key* "\C-xe" 'end-of-buffer)
(bind-key* [(control end)] 'end-of-buffer)
(bind-key* [C-kp-home] 'beginning-of-buffer)
(bind-key* [C-kp-end] 'end-of-buffer)
(bind-key* [C-kp-prior] 'beginning-of-buffer)
(bind-key* [C-kp-next]  'end-of-buffer)
(bind-key* [(control prior)] 'beginning-of-buffer)
(bind-key* [(control next)] 'end-of-buffer)
(bind-key* [(alt f4)] 'save-buffers-kill-emacs)
(bind-key* [(meta f4)] 'save-buffers-kill-emacs)
(bind-key* "\C-x\C-c" 'comment-region)
(bind-key* "\C-x\M-f" 'fill-paragraph)
(bind-key* [(meta down)] 'end-of-defun)
(bind-key* [(meta up)] 'beginning-of-defun)
(bind-key* [(meta I)] 'end-of-defun)
(bind-key* [(meta i)] 'beginning-of-defun)
(bind-key* [(meta r)] 'query-replace)
(bind-key* [M-kp-down] 'end-of-defun)
(bind-key* [M-kp-up] 'beginning-of-defun)
(bind-key* [C-kp-left] 'backward-word)
(bind-key* [C-kp-right] 'forward-word)
(bind-key* "\C-s" 'isearch-forward)
(bind-key* [(control o)] 'other-window)
(bind-key* [(control y)] 'kill-line)
(bind-key* [(control e)] 'next-error)
(bind-key* [(control p)] 'previous-error)
(bind-key* "\C-xg" 'goto-line)
(bind-key* [(control l)] 'goto-line)
(bind-key* [(control L)] 'recenter-top-bottom)
(bind-key* "\C-cg" 'goto-line)
(bind-key* "\C-xc" 'compile)
(bind-key* [f2]  'delete-other-windows)
(bind-key* [(control w)] 'call-last-kbd-macro)
(bind-key* [mouse-3] 'mouse-major-mode-menu)
(bind-key* [(control j)] 'completion-at-point)
(bind-key* [(control z)] 'undo)

(bind-key* "\C-x\C-z" 'repeat)

(bind-key* [(control ?\))] 'forward-list)
(bind-key* [(control ?\()] 'backward-list)
(bind-key* [(meta j)] 'next-line)
(bind-key* [(meta e)] 'end-of-line)
(bind-key* [(meta j)] 'next-line)
(bind-key* [(meta k)] 'previous-line)
(bind-key* [(meta h)] 'backward-char)
(bind-key* [(meta l)] 'forward-char)
(bind-key* [(meta p)] 'match-paren)
(bind-key* [(meta n)] 'my-scroll-up)
(bind-key* [(meta o)] 'my-scroll-down)
(bind-key* [(meta m)] 'my-scroll-up)
